services:
  postgres:
    image: postgres:16-alpine
    container_name: llm-uni-assistant-db
    environment:
      POSTGRES_DB: llm_uni_assistant
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/dbinit/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
      - ./src/main/resources/dbinit/seed_students.sql:/docker-entrypoint-initdb.d/02_dump.sql:ro
      - ./src/main/resources/dbinit/seed_subjects.sql:/docker-entrypoint-initdb.d/03_dump.sql:ro
      - ./src/main/resources/dbinit/seed_professors.sql:/docker-entrypoint-initdb.d/04_dump.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_user -d llm_uni_assistant" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: llm-uni-assistant-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:6333/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data: