CREATE TABLE users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name          TEXT NOT NULL,
    surname       TEXT NOT NULL
);

CREATE TYPE user_role AS ENUM ('student', 'professor', 'admin');

CREATE TABLE user_roles
(
    user_id BIGINT    NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    role    user_role NOT NULL,
    PRIMARY KEY (user_id, role)
);

CREATE TABLE professors
(
    professor_id BIGINT PRIMARY KEY
        REFERENCES users (user_id) ON DELETE CASCADE,
    short_name   TEXT NOT NULL
);

CREATE TABLE students
(
    student_id    BIGINT PRIMARY KEY
        REFERENCES users (user_id) ON DELETE CASCADE,
    student_index BIGINT NOT NULL UNIQUE
);

CREATE TABLE subjects
(
    subject_id BIGSERIAL PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    short_name TEXT NOT NULL UNIQUE,
    code       TEXT NOT NULL UNIQUE
);

CREATE TABLE professor_group_subjects
(
    group_subject_id BIGSERIAL PRIMARY KEY,
    subject_id       BIGINT NOT NULL REFERENCES subjects (subject_id),
    short_name       TEXT   NOT NULL UNIQUE
);

CREATE TABLE professor_group_subject_members
(
    group_subject_id BIGINT NOT NULL REFERENCES professor_group_subjects (group_subject_id),
    professor_id     BIGINT NOT NULL REFERENCES professors (professor_id),
    PRIMARY KEY (group_subject_id, professor_id)
);

CREATE TABLE enrollments
(
    user_id          BIGINT  NOT NULL REFERENCES users (user_id),
    group_subject_id BIGINT  NOT NULL REFERENCES professor_group_subjects (group_subject_id),
    can_use_llm      BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (user_id, group_subject_id)
);

CREATE TABLE llm_controls
(
    group_subject_id BIGINT PRIMARY KEY
        REFERENCES professor_group_subjects (group_subject_id) ON DELETE CASCADE,
    model_name       TEXT,
    llm_provider      TEXT,
    instructions     TEXT,
    params           JSONB DEFAULT '{}'::jsonb
);

CREATE TYPE resource_kind AS ENUM ('file', 'link', 'note');

CREATE TABLE llm_resources
(
    resource_id      BIGSERIAL PRIMARY KEY,
    group_subject_id BIGINT        NOT NULL
        REFERENCES professor_group_subjects (group_subject_id) ON DELETE CASCADE,
    kind             resource_kind NOT NULL,
    title            TEXT          NOT NULL,

    url              TEXT,
    file_uri         TEXT,
    mime_type        TEXT,
    size_bytes       BIGINT,

    checksum         TEXT,
    description      TEXT
);

CREATE TYPE message_origin AS ENUM ('user', 'assistant');

CREATE TABLE chat_sessions
(
    session_id       BIGSERIAL PRIMARY KEY,
    user_id          BIGINT      NOT NULL REFERENCES users (user_id),
    group_subject_id BIGINT      NOT NULL REFERENCES professor_group_subjects (group_subject_id),

    title            TEXT,

    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_session_enrollment
        FOREIGN KEY (user_id, group_subject_id)
            REFERENCES enrollments (user_id, group_subject_id)
            ON DELETE CASCADE
);

CREATE TABLE chat_messages
(
    message_id BIGSERIAL PRIMARY KEY,
    session_id BIGINT         NOT NULL
        REFERENCES chat_sessions (session_id) ON DELETE CASCADE,
    origin     message_origin NOT NULL,
    content    TEXT           NOT NULL,
    created_at TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);
